### PR TITLE
updated for swift 3

### PR DESCRIPTION
**Pull request by RishabhTayal**
The current PR is for `master` branch. Please create a new branch for swift 3.

### CODE REVIEW

**Comment by RishabhTayal** [comment]
Fixes: https://github.com/Ramotion/animated-tab-bar/issues/124

**Comment by tjdaniel2** [comment]
I'm not sure if I'm leaving this in the right place but I'm getting a few errors in the RAMFumeAnimiation file "no '+' candidates produce the expected contextual result type 'AnyObject'" at all the playMoveIconAnimation calls

**Comment by RishabhTayal** [comment]
Which Xcode are you using? I have not updated this for the Xcode 8 release.

**Comment by tjdaniel2** [comment]
Ok, there's my problem then. I'm using Xcode 8 but so far thats my only problem with it.

**Pull request closed without merging**
